Revert "l2tp: ensure session can't get removed during pppol2tp_session_ioctl()"
This reverts commit c8e353d60ccff349ab11c95ed92865b491aebd1f.

Getting the following kernel compile error:

l2tp_ppp.c:1159:5: error: implicit declaration of function 'l2tp_sessi
on_get' [-Werror=implicit-function-declaration]

Signed-off-by: Marc Babad <blitzkrieg.marc02@gmail.com>